theme: jekyll-theme-cayman
title: "Langauge Learning Resources"
description: "A website full of Lists of resources to help learn (human) langauges"
show_downloads: false
github:
   is_project_page: false
